"""Offline woodland dressing shared by all six war maps.

Return native scene text; nothing is generated by the running game. Tree
groves and their navigation radii mirror across x=0. Shore stones follow the
actual bank on each side, including its asymmetric shelves and rounded coves.
"""
from __future__ import annotations

from collections import defaultdict
import math
import random
from war_nature_placement import ShoreSupport
from block_war_height_authoring import field, height_at, supported_footprint, triangle


NATURE = "res://assets/models/block_war/nature/"
TREES = ("canopy_oak", "silver_birch", "wind_pine", "weeping_willow")
SMALL = ("fern_patch", "meadow_tuft", "daisies", "bluebells", "reed_cluster")
SCENES = TREES + ("hazel_thicket", "moss_boulder")
PALETTES = {
    "rift": ("weeping_willow", "canopy_oak", "silver_birch", "wind_pine"),
    "lake": ("canopy_oak", "silver_birch", "canopy_oak", "silver_birch", "wind_pine"),
    "rivers": ("canopy_oak", "canopy_oak", "silver_birch", "wind_pine"),
    "ridges": ("wind_pine", "wind_pine", "silver_birch", "canopy_oak"),
    "islands": ("canopy_oak", "silver_birch", "wind_pine", "canopy_oak"),
    "highland": ("wind_pine", "silver_birch", "wind_pine", "canopy_oak"),
    "terraces": ("silver_birch", "canopy_oak", "silver_birch", "canopy_oak"),
    "switchback": ("wind_pine", "wind_pine", "silver_birch", "canopy_oak"),
    "crown": ("canopy_oak", "wind_pine", "silver_birch", "canopy_oak"),
}


def _vector(values, kind="Vector3"):
    return kind + "(" + ", ".join(f"{v:.6f}".rstrip("0").rstrip(".") if v else "0" for v in values) + ")"


def _inside(rect, x, z, margin=0.0):
    rx, rz, width, height = rect
    return rx - margin <= x <= rx + width + margin and rz - margin <= z <= rz + height + margin


def _distance_to_path(x, z, segment):
    x1, z1, x2, z2 = segment
    dx, dz = x2 - x1, z2 - z1
    length_squared = dx * dx + dz * dz
    t = max(0.0, min(1.0, ((x - x1) * dx + (z - z1) * dz) / max(length_squared, 0.0001)))
    return math.hypot(x - x1 - t * dx, z - z1 - t * dz)


def author_nature(layout, paths):
    """Return (external resources, subresources, Nature child nodes).

    ``paths`` is a sequence of (x1, z1, x2, z2) soil-road segments.  Buildings
    keep a clear yard, the full marching lanes stay open, and bridge mouths
    remain visible.  All obstacle metadata stores a local radius because
    WarMap multiplies it by the scene node's x scale when baking routes.
    """
    map_id = layout["id"]
    hx, hz = layout["half"]
    waters, mountains, bridges = layout["water"], layout["mountains"], layout["bridges"]
    buildings = layout["buildings"]
    obstacle_paths = list(paths)
    if map_id == "rift":
        # The central road runs through the tower, but armies pass on either
        # side. Keep both actual lanes open between the tower and the coves.
        obstacle_paths.extend((x, -6.0, x, 6.0) for x in (-4.0, 4.0))
    rng = random.Random(925730 + sum((i + 1) * ord(char) for i, char in enumerate(map_id)))
    externals = [f'[ext_resource type="PackedScene" path="{NATURE}{name}.tscn" id="nature_{name}"]' for name in SCENES]
    externals += [f'[ext_resource type="ArrayMesh" path="{NATURE}{name}_combined.res" id="nature_{name}_mesh"]' for name in SMALL if name != "reed_cluster"]
    externals.append(f'[ext_resource type="ArrayMesh" path="{NATURE}reed_cluster_grass.res" id="nature_reed_cluster_mesh"]')
    externals.append(f'[ext_resource type="Material" path="{NATURE}grass.tres" id="nature_grass_material"]')
    resources, nodes = [], []
    batches = defaultdict(list)
    occupied = []
    tree_sites = []
    sequence = 0
    support = ShoreSupport(map_id, waters) if waters else None
    rock_sites = []

    def on_land(x, z, radius=0.0, allow_mountain=False):
        if abs(x) > hx + 21 or abs(z) > hz + 21:
            return False
        exclusions = waters if allow_mountain else waters + mountains
        return not any(_inside(rect, x, z, radius) for rect in exclusions)

    def clear_site(x, z, footprint, road_gap=3.4, yard=7.2, allow_mountain=False):
        if not supported_footprint(layout, x, z, footprint + 0.3):
            return False
        if not on_land(x, z, footprint, allow_mountain):
            return False
        if any(_inside(rect, x, z, footprint + 3.0) for rect in bridges):
            return False
        if any(math.hypot(x - building[0], z - building[1]) < yard + footprint for building in buildings):
            return False
        return all(_distance_to_path(x, z, segment) >= road_gap + footprint for segment in obstacle_paths)

    def scene(species, x, z, size, yaw, label, y=0.0, proportions=(1.0, 1.0, 1.0), radius=0.0, tilt=(0.0, 0.0)):
        nonlocal sequence
        sequence += 1
        scale = tuple(size * component for component in proportions)
        y += height_at(layout, x, z)
        node = (f'[node name="nature_{label}_{sequence:04d}" parent="Nature" instance=ExtResource("nature_{species}")]\n'
                f'position = {_vector((x, y, z))}\nrotation = {_vector((tilt[0], yaw, tilt[1]))}\nscale = {_vector(scale)}')
        if radius > 0 and abs(x) - radius < hx and abs(z) - radius < hz and not any(_inside(rect, x, z) for rect in mountains):
            node += f'\nmetadata/route_radius = {radius / scale[0]:.6f}'
        nodes.append(node)

    def groundcover(species, x, z, size, yaw, y=-0.015, shoreline=False):
        # Flowers and grass are low decoration, never navigation obstacles.
        supported = any(_inside(rect, x, z, -0.12) for rect in waters) if shoreline else on_land(x, z, 0.12)
        if not supported or any(_inside(rect, x, z, 0.35) for rect in bridges) or not supported_footprint(layout, x, z, size * 0.65, 0.25):
            return
        if any(math.hypot(x - b[0], z - b[1]) < 3.6 for b in buildings):
            return
        if any(_distance_to_path(x, z, segment) < 1.6 for segment in paths):
            return
        cell = (species, math.floor(x / 32), math.floor(z / 32))
        batches[cell].append((x, y + height_at(layout, x, z), z, size, yaw))

    def flower_pair(species, x, z, size, yaw):
        for sign in (-1, 1):
            groundcover(species, sign * abs(x), z, size, yaw * sign)

    def tree_fits(x, z, species, size, reserved):
        x = abs(x)
        crown = (2.4 if species == "canopy_oak" else 2.1) * size
        if x < crown + 0.4:
            return False
        # Crown clearance keeps buildings and bridgeheads readable.  Crowns in
        # the same grove may overlap, while their trunks retain breathing room.
        if not all(clear_site(sign * x, z, crown, road_gap=2.8, yard=6.5) for sign in (-1, 1)):
            return False
        spacing = 1.02 * size
        if any(math.hypot(x - ox, z - oz) < spacing + old_spacing for ox, oz, old_spacing in reserved):
            return False
        return True

    def tree_pair(x, z, species, size, yaw, label="Tree"):
        x = abs(x)
        if not tree_fits(x, z, species, size, occupied):
            return False
        spacing = 1.02 * size
        occupied.append((x, z, spacing))
        for sign in (-1, 1):
            scene(species, sign * x, z, size, yaw * sign, label, radius=0.72 * size)
            tree_sites.append((sign * x, z, size))
        return True

    def stone_pair(x, z, size, yaw, label="Outcrop", proportions=(1.1, 0.83, 0.85)):
        x = abs(x)
        footprint = size * max(proportions[0], proportions[2]) * 1.05
        if x < footprint + 0.3:
            return False
        if not all(clear_site(sign * x, z, footprint, road_gap=3.0, yard=5.0) for sign in (-1, 1)):
            return False
        if any(math.hypot(x - ox, z - oz) < footprint + spacing for ox, oz, spacing in occupied):
            return False
        occupied.append((x, z, footprint))
        for sign in (-1, 1):
            scene("moss_boulder", sign * x, z, size, yaw * sign, label, y=-0.11 * size * proportions[1], proportions=proportions, radius=footprint)
            rock_sites.append((sign * x, z, footprint))
        return True

    def shore_clear(x, z, radius):
        return (abs(x) < hx + 9 and abs(z) < hz + 9
                and not any(_inside(rect, x, z, radius + 4.0) for rect in bridges)
                and all(math.hypot(x - b[0], z - b[1]) > radius + 5 for b in buildings)
                and all(_distance_to_path(x, z, path) > radius + 2.8 for path in obstacle_paths)
                and all(math.hypot(x - ox, z - oz) > radius + old_radius + .18 for ox, oz, old_radius in rock_sites))

    # Three separate rock teeth with clear contact shadows. Their horizontal
    # footprints fit the ridge instead of stretching one rock through another.
    for ridge_index, (rx, rz, width, length) in enumerate(mountains):
        center_x = rx + width * 0.5
        width_scale, length_scale = width / 12.0, length / 20.0
        height_scale = math.sqrt(min(width_scale, length_scale))
        variations = [(rng.uniform(-0.3, 0.3), rng.uniform(-0.35, 0.35))
                      for _ in range(max(3, int(length / 3.7)))]
        direction = 1 if ridge_index % 2 == 0 else -1
        summits = ((-.65, 0.20, 2.70, 4.2, 2.4, .18, 0.0, 0.0),
                   (.60, 0.50, 2.85, 5.6, 2.45, -.24, 0.0, 0.0),
                   (-.45, 0.80, 2.45, 3.1, 2.25, .30, 0.0, 0.0))
        for index, (dx, t, sx, sy, sz, yaw, pitch, roll) in enumerate(summits):
            local_t = t if direction == 1 else 1.0 - t
            scene("moss_boulder", center_x + dx * direction * width_scale, rz + length * local_t, 1.0,
                  yaw * direction, f"Ridge{ridge_index}Summit", y=-0.11 * (sy + variations[index][0]) * height_scale,
                  proportions=(sx * width_scale, (sy + variations[index][0]) * height_scale, sz * length_scale), tilt=(pitch * direction, roll))
        # Scree appears in three unequal pockets, never in evenly spaced rows.
        pockets = ((-4.15, 0.37, 0.84, 0.7), (4.10, 0.66, 0.74, 2.35), (-3.65, 0.90, 0.55, -0.65))
        for index, (dx, t, size, yaw) in enumerate(pockets):
            px = center_x + dx * direction * width_scale
            pz = rz + length * (t if direction == 1 else 1.0 - t)
            scene("moss_boulder", px, pz, size, yaw * direction,
                  f"Ridge{ridge_index}Scree", y=-0.13 * size * height_scale, proportions=(1.18 * width_scale, 1.15 * height_scale, 1.22 * length_scale))
            scene("moss_boulder", px + math.copysign(0.35 * width_scale, dx), pz + direction * 1.65 * length_scale, size * 0.40,
                  yaw + 1.4, f"Ridge{ridge_index}Chip", y=-0.07 * height_scale, proportions=(1.2 * width_scale, 0.72 * height_scale, length_scale))
        for index, (dx, t, size) in enumerate(((-4.7, 0.61, 0.62), (4.6, 0.19, 0.52), (4.7, 0.88, 0.57))):
            px = center_x + dx * direction * width_scale
            pz = rz + length * (t if direction == 1 else 1.0 - t)
            scene("wind_pine", px, pz, size * min(width_scale, length_scale), variations[-1][1] + index * 1.7,
                  f"Ridge{ridge_index}Pine", y=-0.01)
            scene("hazel_thicket", px - math.copysign(0.65 * width_scale, dx * direction), pz + 0.6 * length_scale,
                  (0.57 + index * 0.07) * min(width_scale, length_scale), variations[-2][1] + index, f"Ridge{ridge_index}Shrub")

    # Sparse groups follow the actual sculpted shoreline. Each boulder needs a
    # level supporting footprint; chips have a real gap rather than intersecting.
    shore_sites = set()
    for rx, rz, width, length in waters:
        edges = ((rx, rz, rx, rz + length, -1, 0),
                 (rx + width, rz, rx + width, rz + length, 1, 0),
                 (rx, rz, rx + width, rz, 0, -1),
                 (rx, rz + length, rx + width, rz + length, 0, 1))
        for x1, z1, x2, z2, nx, nz in edges:
            samples = max(1, int(math.hypot(x2 - x1, z2 - z1) / 9.0))
            for index in range(samples):
                t = (index + 0.5) / samples
                x, z = x1 + (x2 - x1) * t, z1 + (z2 - z1) * t
                if not on_land(x + nx * 0.25, z + nz * 0.25):
                    continue
                px, pz = abs(x + nx * 1.45), z + nz * 1.45
                if abs(px) > hx + 8 or abs(pz) > hz + 8:
                    continue
                key = (round(px * 0.25), round(pz * 0.25))
                if key in shore_sites:
                    continue
                shore_sites.add(key)
                size, yaw = rng.uniform(0.78, 1.14), rng.uniform(0, math.tau)
                phase = int(abs(x1) + abs(z1) * .1) % 3
                if samples <= 4 or index % 3 == phase:
                    for part, (along, factor) in enumerate(((0.0, 1.0), (1.8, .43))):
                        for sign in (-1, 1):
                            radius = size * factor * 1.13
                            seat = support.seat(sign * abs(x + nz * along), z - nx * along,
                                                radius, size * factor * .9, shore_clear)
                            if seat is None:
                                continue
                            bx, by, bz = seat
                            scene("moss_boulder", bx, bz, size * factor, (yaw + part * 1.65) * sign,
                                  "BankStone", y=by, proportions=(1.05, .9, .88), radius=radius)
                            rock_sites.append((bx, bz, radius))
                            occupied.append((abs(bx), bz, radius + .25))
                            # Reeds root in this dry supporting shelf as well.
                            tx, tz = bx + nx * (radius + .32), bz + nz * (radius + .32)
                            ty = support.height(tx, tz)
                            if ty is not None:
                                groundcover("reed_cluster", tx, tz, .7, yaw, y=ty - .025,
                                            shoreline=any(_inside(w, tx, tz, -.12) for w in waters))
                if index % 3 == 1 and map_id in ("lake", "rivers", "islands"):
                    tree_pair(abs(x + nx * 3.2), z + nz * 3.2,
                              "weeping_willow", rng.uniform(0.72, 0.88), yaw, "WatersideWillow")

    def species_at(z, grove_index):
        if map_id == "islands":
            palette = (("silver_birch", "canopy_oak", "silver_birch") if z < -18 else
                       ("canopy_oak", "canopy_oak", "silver_birch") if z < 18 else
                       ("wind_pine", "canopy_oak", "wind_pine"))
        else:
            palette = PALETTES[map_id]
        return palette[grove_index % len(palette)]

    target = 140 if hx <= 40 else 220 if hx <= 60 else 320
    interior_target = int(target * 0.34)
    # Grove placement uses a separate RNG stream from the shoreline.  A later
    # shoreline refinement does not reshuffle every inland tree and route.
    grove_rng = random.Random(925911 + sum(ord(c) for c in map_id))
    planted_groves = []

    def grove(cx, cz, grove_index, exterior=False):
        # Accept a whole group, never the isolated survivor of six rejected
        # candidates. Mature trees form a joined canopy; young trees soften its
        # edge. A separate gap between groups preserves broad open clearings.
        if any(math.hypot(cx - ox, cz - oz) < (8.5 if exterior else 10.0) for ox, oz in planted_groves):
            return False
        planned = []
        reserved = occupied.copy()
        dominant = species_at(cz, grove_index)
        for index in range(9 if exterior else 7):
            angle = index * 2.399963 + grove_index * .73
            spread = 0.0 if index == 0 else 1.6 * math.sqrt(index)
            x, z = cx + math.cos(angle) * spread, cz + math.sin(angle) * spread * .77
            if exterior and abs(x) < hx + 2.2 and abs(z) < hz + 2.2:
                continue
            if not exterior and (abs(x) > hx - 2 or abs(z) > hz - 2):
                continue
            size = grove_rng.uniform(.57, .72) if index >= 4 else grove_rng.uniform(.87, 1.10)
            species = dominant if index % 3 else species_at(cz, grove_index + 1)
            if tree_fits(x, z, species, size, reserved):
                planned.append((x, z, species, size, angle))
                reserved.append((abs(x), z, 1.02 * size))
        # Rejected sites can leave an outlying sapling. Keep only the connected
        # body of the grove, with two nearby neighbours for each retained tree.
        for _ in range(len(planned)):
            connected = [tree for tree in planned if sum(
                math.hypot(tree[0] - other[0], tree[1] - other[1]) < 5.7
                for other in planned if other is not tree) >= 2]
            if len(connected) == len(planned):
                break
            planned = connected
        if len(planned) < (4 if exterior else 3):
            return False
        for x, z, species, size, angle in planned:
            assert tree_pair(x, z, species, size, angle, "ForestTree" if exterior else "ClearingTree")
        planted_groves.append((cx, cz))
        return True

    for grove_index in range(180):
        if len(tree_sites) >= interior_target:
            break
        cx = grove_rng.uniform(5.0, hx - 4.0)
        cz = grove_rng.uniform(-hz + 4.0, hz - 4.0)
        grove(cx, cz, grove_index)

    # Thick, irregular forest islands frame the map, with gaps rather than an
    # evenly spaced fence.  All centers are outside the playable rectangle.
    grove_centers = []
    for z in range(-int(hz) + 2, int(hz), 15):
        grove_centers.append((hx + grove_rng.uniform(5.0, 10.0), z + grove_rng.uniform(-2.0, 2.0)))
    for x in range(6, int(hx) + 4, 15):
        for sign in (-1, 1):
            grove_centers.append((x + grove_rng.uniform(-2.0, 2.0), sign * (hz + grove_rng.uniform(5.0, 10.0))))
    grove_rng.shuffle(grove_centers)
    for layer in range(2):
        for grove_index, (cx, cz) in enumerate(grove_centers):
            if len(tree_sites) >= target:
                break
            grove(cx + layer * 6.5, cz + layer * 5.5, grove_index, exterior=True)

    # Understory follows tree groups, retaining open ground between them.
    for index, (x, z, size) in enumerate(site for site in tree_sites if site[0] > 0):
        yaw = rng.uniform(0, math.tau)
        flower_pair("fern_patch", x + 0.55, z + 0.45, size * 0.72, yaw)
        flower_pair("meadow_tuft", x - 0.50, z + 0.65, size * 0.82, yaw + 1.2)
        if index % 6 == 0:
            flower_pair("bluebells" if map_id in ("lake", "ridges") else "daisies",
                        x + 0.8, z - 0.7, size * 0.68, yaw)
        if index % 4 == 0:
            px, pz = x + 1.35, z + 0.45
            if all(clear_site(sign * px, pz, 0.65, road_gap=2.5, yard=5.0) for sign in (-1, 1)):
                for sign in (-1, 1):
                    scene("hazel_thicket", sign * px, pz, size * 0.65, yaw * sign, "Understory", radius=0.50 * size)
        if index % 12 == 0:
            stone_pair(x + 2.2, z - 1.0, rng.uniform(0.48, 0.75), yaw, "ForestRock")

    # Sparse low verges articulate turns and settlement outskirts, instead of
    # putting the same ten plants in a ring around every single building.
    for road_index, segment in enumerate(paths):
        x1, z1, x2, z2 = segment
        length = math.hypot(x2 - x1, z2 - z1)
        if length < 3:
            continue
        nx, nz = -(z2 - z1) / length, (x2 - x1) / length
        for step in range(max(1, int(length / 7.5))):
            t = (step + 0.5) / max(1, int(length / 7.5))
            for sign in (-1, 1):
                x, z = x1 + (x2 - x1) * t + nx * sign * 2.5, z1 + (z2 - z1) * t + nz * sign * 2.5
                if x < 0 or abs(x) > hx or abs(z) > hz:
                    continue
                flower_pair("meadow_tuft", x, z, rng.uniform(0.54, 0.74), road_index)
                if (step + road_index) % 4 == 0:
                    flower_pair("daisies", x + nx * 0.5, z + nz * 0.5, 0.57, road_index)

    # Rock appears in separated seams and pockets on the baked cliff faces.
    # This stream is independent of trees/shorelines and never alters obstacles.
    if layout.get("terrain"):
        meta, grid = field(map_id)
        step = meta["cell_size"]
        origin_x, origin_z = meta["origin"]
        cliff_rng = random.Random(732419 + sum((i + 1) * ord(c) for i, c in enumerate(map_id)))
        patch_phase = cliff_rng.uniform(0, math.tau)
        cliff_sites, cliff_rocks = [], []

        def cliff_clear(x, z, radius):
            return (x > radius + .3 and x + radius < hx and abs(z) + radius < hz
                    and all(on_land(sign * x, z, radius) for sign in (-1, 1))
                    and all(math.hypot(sign * x - b[0], z - b[1]) >= 6.1 + radius
                            for sign in (-1, 1) for b in buildings)
                    and all(_distance_to_path(sign * x, z, path) >= 2.8 + radius
                            for sign in (-1, 1) for path in obstacle_paths)
                    and all(not _inside(bridge, sign * x, z, 3.0 + radius)
                            for sign in (-1, 1) for bridge in bridges))

        def polygons_overlap(a, b):
            # Separating axes test: a narrow walkable triangle cannot hide
            # between footprint samples or beneath a diagonal edge of a rock.
            for polygon in (a, b):
                for index, start in enumerate(polygon):
                    end = polygon[(index + 1) % len(polygon)]
                    nx, nz = start[1] - end[1], end[0] - start[0]
                    first = [px * nx + pz * nz for px, pz in a]
                    second = [px * nx + pz * nz for px, pz in b]
                    if max(first) < min(second) or max(second) < min(first):
                        return False
            return True

        def steep_footprint(x, z, size, yaw, proportions):
            # Conservative bounds of the existing moss_boulder mesh, with no
            # pitch/roll. Flat slabs reuse that mesh with a lower Y proportion.
            rx, rz = 1.04 * size * proportions[0], .83 * size * proportions[2]
            cosine, sine = math.cos(yaw), math.sin(yaw)
            corners = [(x + u * cosine + v * sine, z - u * sine + v * cosine)
                       for u, v in ((-rx, -rz), (rx, -rz), (rx, rz), (-rx, rz))]
            min_x = math.floor((min(p[0] for p in corners) - origin_x) / step)
            max_x = math.floor((max(p[0] for p in corners) - origin_x) / step)
            min_z = math.floor((min(p[1] for p in corners) - origin_z) / step)
            max_z = math.floor((max(p[1] for p in corners) - origin_z) / step)
            if min_x < 0 or min_z < 0 or max_x >= meta["width"] - 1 or max_z >= meta["depth"] - 1:
                return False
            for iz in range(min_z, max_z + 1):
                for ix in range(min_x, max_x + 1):
                    px, pz = origin_x + ix * step, origin_z + iz * step
                    a, b, c, d = (float(grid[iz, ix]), float(grid[iz, ix + 1]),
                                  float(grid[iz + 1, ix]), float(grid[iz + 1, ix + 1]))
                    for vertices, dx, dz in (
                            (((px, pz), (px + step, pz), (px, pz + step)), b - a, c - a),
                            (((px + step, pz), (px + step, pz + step), (px, pz + step)), d - c, d - b)):
                        if math.hypot(dx, dz) / step <= .5001 and polygons_overlap(corners, vertices):
                            return False
            return True

        candidates = []
        for iz in range(1, meta["depth"] - 1, 3):
            for ix in range(1, meta["width"] - 1, 3):
                x = origin_x + ix * step + cliff_rng.uniform(-.24, .24)
                z = origin_z + iz * step + cliff_rng.uniform(-.24, .24)
                if not 1.5 < x < hx - 1 or abs(z) >= hz - 1:
                    continue
                # Broad coherent gaps, rather than a constant-spacing stone rim.
                patch = math.sin(x * .27 + z * .19 + patch_phase) + .55 * math.cos(z * .31 - x * .13)
                height, dx, dz = triangle(layout, x, z)
                slope = math.hypot(dx, dz)
                if patch > -.05 and height > .45 and slope > .85 and cliff_clear(x, z, .45):
                    candidates.append((x, z, dx / slope, dz / slope))
        cliff_rng.shuffle(candidates)
        budget = 12 if hx <= 40 else 18 if hx <= 60 else 26
        for x, z, nx, nz in candidates:
            if len(cliff_sites) >= budget:
                break
            if any(math.hypot(x - ox, z - oz) < gap for ox, oz, gap in cliff_sites):
                continue
            tx, tz = -nz, nx
            yaw = math.atan2(-tz, tx)
            planned = []
            # One taller embedded tooth, one shelf and one or two broken chips.
            parts = ((0.0, 0.0, cliff_rng.uniform(.66, .88), (1.25, 1.35, .55)),
                     (cliff_rng.uniform(-1.65, -1.15), .08, cliff_rng.uniform(.45, .62), (1.35, .58, .64)),
                     (cliff_rng.uniform(1.15, 1.7), -.08, cliff_rng.uniform(.36, .53), (1.12, .86, .70)))
            if cliff_rng.random() < .45:
                parts += ((cliff_rng.uniform(-.5, .6), -.45, .30, (1.2, .60, .70)),)
            for along, outward, size, proportions in parts:
                px, pz = x + tx * along - nx * outward, z + tz * along - nz * outward
                rotation = yaw + cliff_rng.uniform(-.14, .14)
                radius = size * math.hypot(1.04 * proportions[0], .83 * proportions[2])
                # Even the conservative bounding circle fits inside the 2.1m
                # formation exclusion. The stronger triangle test below keeps
                # the entire visible footprint off every traversable ramp face.
                if radius > 1.45 or not cliff_clear(px, pz, radius):
                    continue
                if any(math.hypot(px - ox, pz - oz) < .72 * (radius + old_radius)
                       for ox, oz, old_radius in cliff_rocks):
                    continue
                if not all(steep_footprint(sign * px, pz, size, rotation * sign, proportions) for sign in (-1, 1)):
                    continue
                planned.append((px, pz, size, rotation, proportions, radius))
            if len(planned) < 2:
                continue
            cliff_sites.append((x, z, cliff_rng.uniform(6.5, 9.5)))
            for px, pz, size, rotation, proportions, radius in planned:
                cliff_rocks.append((px, pz, radius))
                for sign in (-1, 1):
                    scene("moss_boulder", sign * px, pz, size, rotation * sign, "CliffCluster",
                          y=-.40 * size * proportions[1], proportions=proportions, radius=0.0)
            # A few small ferns take root at the lower shoulder, not a green
            # necklace around the whole hill. Their roots stay near the rock.
            if len(cliff_sites) == 1 or cliff_rng.random() < .42:
                px, pz, *_ = min(planned, key=lambda part: height_at(layout, part[0], part[1]))
                _, dx, dz = triangle(layout, px, pz)
                slope = math.hypot(dx, dz)
                for distance in (.45, .85, 1.2, 1.55, 1.75):
                    fx, fz = px - dx / slope * distance, pz - dz / slope * distance
                    if cliff_clear(fx, fz, .24) and all(supported_footprint(layout, sign * fx, fz, .24, .18) for sign in (-1, 1)):
                        for sign in (-1, 1):
                            groundcover("fern_patch", sign * fx, fz, .34, sign * yaw)
                        break

    for (species, cell_x, cell_z), instances in sorted(batches.items()):
        identifier = f"nature_cover_{species}_{cell_x}_{cell_z}".replace("-", "n")
        buffer = []
        for x, y, z, size, yaw in instances:
            cosine, sine = math.cos(yaw) * size, math.sin(yaw) * size
            buffer.extend((cosine, 0, sine, x, 0, size, 0, y, -sine, 0, cosine, z))
        cover_height = max(5.0, max(item[1] for item in instances) + 3.0)
        resources.append(f'[sub_resource type="MultiMesh" id="{identifier}"]\n'
                         f'transform_format = 1\ninstance_count = {len(instances)}\n'
                         f'mesh = ExtResource("nature_{species}_mesh")\n'
                         f'custom_aabb = AABB({cell_x * 32 - 2}, -1, {cell_z * 32 - 2}, 36, {cover_height:g}, 36)\n'
                         f'buffer = PackedFloat32Array({", ".join(f"{value:.6f}" for value in buffer)})')
        nodes.append(f'[node name="{identifier}" type="MultiMeshInstance3D" parent="Nature"]\n'
                     f'multimesh = SubResource("{identifier}")\nmaterial_override = ExtResource("nature_grass_material")\ncast_shadow = 0')
    return externals, resources, nodes
