"""Offline woodland dressing shared by the five additional war maps.

Return native scene text; nothing is generated by the running game.  Tree
groves, dry-shore stones and their navigation radii are mirrored across x=0.
The original sculpted assets and materials remain unchanged.
"""
from __future__ import annotations

from collections import defaultdict
import math
import random


NATURE = "res://assets/models/block_war/nature/"
TREES = ("canopy_oak", "silver_birch", "wind_pine", "weeping_willow")
SMALL = ("fern_patch", "meadow_tuft", "daisies", "bluebells", "reed_cluster")
SCENES = TREES + ("hazel_thicket", "moss_boulder")
PALETTES = {
    "lake": ("canopy_oak", "silver_birch", "canopy_oak", "silver_birch", "wind_pine"),
    "rivers": ("canopy_oak", "canopy_oak", "silver_birch", "wind_pine"),
    "ridges": ("wind_pine", "wind_pine", "silver_birch", "canopy_oak"),
    "islands": ("canopy_oak", "silver_birch", "wind_pine", "canopy_oak"),
    "highland": ("wind_pine", "silver_birch", "wind_pine", "canopy_oak"),
}


def _vector(values, kind="Vector3"):
    return kind + "(" + ", ".join(f"{v:.6f}".rstrip("0").rstrip(".") if v else "0" for v in values) + ")"


def _inside(rect, x, z, margin=0.0):
    rx, rz, width, height = rect
    return rx - margin <= x <= rx + width + margin and rz - margin <= z <= rz + height + margin


def _distance_to_path(x, z, segment):
    x1, z1, x2, z2 = segment
    dx, dz = x2 - x1, z2 - z1
    length_squared = dx * dx + dz * dz
    t = max(0.0, min(1.0, ((x - x1) * dx + (z - z1) * dz) / max(length_squared, 0.0001)))
    return math.hypot(x - x1 - t * dx, z - z1 - t * dz)


def author_nature(layout, paths):
    """Return (external resources, subresources, Nature child nodes).

    ``paths`` is a sequence of (x1, z1, x2, z2) soil-road segments.  Buildings
    keep a clear yard, the full marching lanes stay open, and bridge mouths
    remain visible.  All obstacle metadata stores a local radius because
    WarMap multiplies it by the scene node's x scale when baking routes.
    """
    map_id = layout["id"]
    hx, hz = layout["half"]
    waters, mountains, bridges = layout["water"], layout["mountains"], layout["bridges"]
    buildings = layout["buildings"]
    rng = random.Random(925730 + sum((i + 1) * ord(char) for i, char in enumerate(map_id)))
    externals = [f'[ext_resource type="PackedScene" path="{NATURE}{name}.tscn" id="nature_{name}"]' for name in SCENES]
    externals += [f'[ext_resource type="ArrayMesh" path="{NATURE}{name}_combined.res" id="nature_{name}_mesh"]' for name in SMALL if name != "reed_cluster"]
    externals.append(f'[ext_resource type="ArrayMesh" path="{NATURE}reed_cluster_grass.res" id="nature_reed_cluster_mesh"]')
    externals.append(f'[ext_resource type="Material" path="{NATURE}grass.tres" id="nature_grass_material"]')
    resources, nodes = [], []
    batches = defaultdict(list)
    occupied = []
    tree_sites = []
    sequence = 0

    def on_land(x, z, radius=0.0, allow_mountain=False):
        if abs(x) > hx + 21 or abs(z) > hz + 21:
            return False
        exclusions = waters if allow_mountain else waters + mountains
        return not any(_inside(rect, x, z, radius) for rect in exclusions)

    def clear_site(x, z, footprint, road_gap=3.4, yard=7.2, allow_mountain=False):
        if not on_land(x, z, footprint, allow_mountain):
            return False
        if any(_inside(rect, x, z, footprint + 3.0) for rect in bridges):
            return False
        if any(math.hypot(x - building[0], z - building[1]) < yard + footprint for building in buildings):
            return False
        return all(_distance_to_path(x, z, segment) >= road_gap + footprint for segment in paths)

    def scene(species, x, z, size, yaw, label, y=0.0, proportions=(1.0, 1.0, 1.0), radius=0.0, tilt=(0.0, 0.0)):
        nonlocal sequence
        sequence += 1
        scale = tuple(size * component for component in proportions)
        node = (f'[node name="nature_{label}_{sequence:04d}" parent="Nature" instance=ExtResource("nature_{species}")]\n'
                f'position = {_vector((x, y, z))}\nrotation = {_vector((tilt[0], yaw, tilt[1]))}\nscale = {_vector(scale)}')
        if radius > 0 and abs(x) < hx and abs(z) < hz and not any(_inside(rect, x, z) for rect in mountains):
            node += f'\nmetadata/route_radius = {radius / scale[0]:.6f}'
        nodes.append(node)

    def groundcover(species, x, z, size, yaw, y=-0.015, shoreline=False):
        # Flowers and grass are low decoration, never navigation obstacles.
        supported = any(_inside(rect, x, z, -0.12) for rect in waters) if shoreline else on_land(x, z, 0.12)
        if not supported or any(_inside(rect, x, z, 0.35) for rect in bridges):
            return
        if any(math.hypot(x - b[0], z - b[1]) < 3.6 for b in buildings):
            return
        if any(_distance_to_path(x, z, segment) < 1.6 for segment in paths):
            return
        cell = (species, math.floor(x / 32), math.floor(z / 32))
        batches[cell].append((x, y, z, size, yaw))

    def flower_pair(species, x, z, size, yaw):
        for sign in (-1, 1):
            groundcover(species, sign * abs(x), z, size, yaw * sign)

    def tree_pair(x, z, species, size, yaw, label="Tree"):
        x = abs(x)
        crown = (2.1 if species in ("canopy_oak", "weeping_willow") else 1.6) * size
        if x < crown + 0.4:
            return False
        # Crown clearance keeps buildings and bridgeheads readable.  Crowns in
        # the same grove may overlap, while their trunks retain breathing room.
        if not all(clear_site(sign * x, z, crown, road_gap=2.8, yard=6.5) for sign in (-1, 1)):
            return False
        spacing = 1.75 * size
        if any(math.hypot(x - ox, z - oz) < spacing + old_spacing for ox, oz, old_spacing in occupied):
            return False
        occupied.append((x, z, spacing))
        for sign in (-1, 1):
            scene(species, sign * x, z, size, yaw * sign, label, radius=0.72 * size)
            tree_sites.append((sign * x, z, size))
        return True

    def stone_pair(x, z, size, yaw, label="Outcrop", proportions=(1.1, 0.83, 0.85), reserve_only=False):
        x = abs(x)
        footprint = size * max(proportions[0], proportions[2]) * 1.05
        if x < footprint + 0.3:
            return False
        if not all(clear_site(sign * x, z, footprint, road_gap=3.0, yard=5.0) for sign in (-1, 1)):
            return False
        if any(math.hypot(x - ox, z - oz) < footprint + spacing for ox, oz, spacing in occupied):
            return False
        occupied.append((x, z, footprint))
        if reserve_only:
            # Keep the same dry-bank planting setback when shoreline dressing
            # changes, without turning that setback into a navigation obstacle.
            return True
        for sign in (-1, 1):
            scene("moss_boulder", sign * x, z, size, yaw * sign, label, y=-0.08, proportions=proportions, radius=footprint)
        return True

    # Three interlocking outcrops give each ridge a broad shoulder, a tall crest
    # and a low tail.  Off-axis centers and distinct rotations break the repeated
    # fracture pattern of the source rock.  Everything stays in excluded ground.
    for ridge_index, (rx, rz, width, length) in enumerate(mountains):
        center_x = rx + width * 0.5
        variations = [(rng.uniform(-0.3, 0.3), rng.uniform(-0.35, 0.35))
                      for _ in range(max(3, int(length / 3.7)))]
        direction = 1 if ridge_index % 2 == 0 else -1
        summits = ((-1.2, 0.26, 2.8, 4.2, 3.8, 0.55, 0.045, -0.035),
                   (1.1, 0.49, 3.45, 6.15, 3.85, 1.72, -0.035, 0.040),
                   (-0.75, 0.76, 2.75, 3.1, 4.1, -1.0, 0.060, 0.030))
        for index, (dx, t, sx, sy, sz, yaw, pitch, roll) in enumerate(summits):
            local_t = t if direction == 1 else 1.0 - t
            scene("moss_boulder", center_x + dx * direction, rz + length * local_t, 1.0,
                  yaw * direction, f"Ridge{ridge_index}Summit", y=-0.27,
                  proportions=(sx, sy + variations[index][0], sz), tilt=(pitch * direction, roll))
        # Scree appears in three unequal pockets, never in evenly spaced rows.
        pockets = ((-3.75, 0.35, 1.18, 0.7), (3.8, 0.66, 0.91, 2.35), (-1.65, 0.88, 0.73, -0.65))
        for index, (dx, t, size, yaw) in enumerate(pockets):
            px = center_x + dx * direction
            pz = rz + length * (t if direction == 1 else 1.0 - t)
            scene("moss_boulder", px, pz, size, yaw * direction,
                  f"Ridge{ridge_index}Scree", y=-0.13, proportions=(1.18, 1.15, 1.22), tilt=(0.12, -0.08))
            scene("moss_boulder", px - math.copysign(0.8, dx), pz + direction * 1.13, size * 0.46,
                  yaw + 1.4, f"Ridge{ridge_index}Chip", y=-0.07, proportions=(1.2, 0.72, 1.0))
        for index, (dx, t, size) in enumerate(((-4.55, 0.59, 0.68), (4.5, 0.22, 0.55), (3.9, 0.86, 0.64))):
            px = center_x + dx * direction
            pz = rz + length * (t if direction == 1 else 1.0 - t)
            scene("wind_pine", px, pz, size, variations[-1][1] + index * 1.7,
                  f"Ridge{ridge_index}Pine", y=-0.01)
            scene("hazel_thicket", px - math.copysign(0.65, dx * direction), pz + 0.6,
                  0.57 + index * 0.07, variations[-2][1] + index, f"Ridge{ridge_index}Shrub")

    # Use dry-side anchors only as planting setbacks.  Visible shore rocks sit
    # lower, in the already excluded bank strip; clusters leave broad gaps and
    # never add new dry-land route obstacles or occupy bridge approaches.
    shore_sites = set()
    for rx, rz, width, length in waters:
        edges = ((rx, rz, rx, rz + length, -1, 0),
                 (rx + width, rz, rx + width, rz + length, 1, 0),
                 (rx, rz, rx + width, rz, 0, -1),
                 (rx, rz + length, rx + width, rz + length, 0, 1))
        for x1, z1, x2, z2, nx, nz in edges:
            samples = max(1, int(math.hypot(x2 - x1, z2 - z1) / 9.0))
            for index in range(samples):
                t = (index + 0.5) / samples
                x, z = x1 + (x2 - x1) * t, z1 + (z2 - z1) * t
                if not on_land(x + nx * 0.25, z + nz * 0.25):
                    continue
                px, pz = abs(x + nx * 1.45), z + nz * 1.45
                if abs(px) > hx + 8 or abs(pz) > hz + 8:
                    continue
                key = (round(px * 0.25), round(pz * 0.25))
                if key in shore_sites:
                    continue
                shore_sites.add(key)
                size, yaw = rng.uniform(0.62, 0.94), rng.uniform(0, math.tau)
                if stone_pair(px, pz, size, yaw, "BankStone", reserve_only=True):
                    reed_sizes = [rng.uniform(0.6, 0.84) for _ in range(3)]
                    phase = int(abs(x1) + abs(z1) * 0.1) % 3
                    if samples <= 4 or index % 3 == phase:
                        positive_normal_x = nx if x + nx * 1.45 >= 0 else -nx
                        edge_x, edge_z = abs(x), z
                        # Large half-buried rock + two smaller overlapping chips.
                        for part, (along, depth, factor) in enumerate(((0.0, 1.2, 1.0), (1.07, 0.64, 0.43), (-0.86, 0.72, 0.32))):
                            bx = edge_x - positive_normal_x * depth + nz * along
                            bz = edge_z - nz * depth - positive_normal_x * along
                            radius = size * factor * 1.15
                            for sign in (-1, 1):
                                if not any(_inside(rect, sign * bx, bz, -radius) for rect in waters):
                                    continue
                                if any(_inside(rect, sign * bx, bz, radius + 3.0) for rect in bridges):
                                    continue
                                scene("moss_boulder", sign * bx, bz, size * factor,
                                      (yaw + part * 1.65) * sign, "BankStone", y=-0.56 if part == 0 else -0.23,
                                      proportions=(1.05, 0.78, 0.88), tilt=(0.10, -0.06))
                        for tuft, reed_size in enumerate(reed_sizes):
                            tx = edge_x - positive_normal_x * 0.78 + nz * (tuft - 1) * 0.62
                            tz = edge_z - nz * 0.78 - positive_normal_x * (tuft - 1) * 0.62
                            for sign in (-1, 1):
                                groundcover("reed_cluster", sign * tx, tz, reed_size,
                                            yaw * sign + tuft, y=-0.48, shoreline=True)
                if index % 3 == 1 and map_id in ("lake", "rivers", "islands"):
                    tree_pair(abs(x + nx * 3.2), z + nz * 3.2,
                              "weeping_willow", rng.uniform(0.72, 0.88), yaw, "WatersideWillow")

    def species_at(z, grove_index):
        if map_id == "islands":
            palette = (("silver_birch", "canopy_oak", "silver_birch") if z < -18 else
                       ("canopy_oak", "canopy_oak", "silver_birch") if z < 18 else
                       ("wind_pine", "canopy_oak", "wind_pine"))
        else:
            palette = PALETTES[map_id]
        return palette[grove_index % len(palette)]

    target = 140 if hx <= 40 else 220 if hx <= 60 else 320
    interior_target = int(target * 0.31)
    # Grove placement uses a separate RNG stream from the shoreline.  A later
    # shoreline refinement does not reshuffle every inland tree and route.
    grove_rng = random.Random(925911 + sum(ord(c) for c in map_id))
    for grove_index in range(100):
        if len(tree_sites) >= interior_target:
            break
        cx = grove_rng.uniform(5.0, hx - 4.0)
        cz = grove_rng.uniform(-hz + 4.0, hz - 4.0)
        for index in range(6):
            angle = index * 2.399963 + grove_index * 0.73
            spread = 0.0 if index == 0 else 2.4 + math.sqrt(index) * 1.45
            x, z = cx + math.cos(angle) * spread, cz + math.sin(angle) * spread * 0.8
            if abs(x) >= hx - 2 or abs(z) >= hz - 2:
                continue
            size = grove_rng.uniform(0.48, 0.66) if index % 4 == 2 else grove_rng.uniform(0.80, 1.04)
            tree_pair(x, z, species_at(cz, grove_index + index), size, angle, "ClearingTree")

    # Thick, irregular forest islands frame the map, with gaps rather than an
    # evenly spaced fence.  All centers are outside the playable rectangle.
    grove_centers = []
    for z in range(-int(hz) + 2, int(hz), 12):
        grove_centers.append((hx + grove_rng.uniform(5.0, 10.0), z + grove_rng.uniform(-2.0, 2.0)))
    for x in range(6, int(hx) + 4, 12):
        for sign in (-1, 1):
            grove_centers.append((x + grove_rng.uniform(-2.0, 2.0), sign * (hz + grove_rng.uniform(5.0, 10.0))))
    grove_rng.shuffle(grove_centers)
    for layer in range(3):
        for grove_index, (cx, cz) in enumerate(grove_centers):
            if len(tree_sites) >= target:
                break
            for index in range(9):
                if len(tree_sites) >= target:
                    break
                angle = index * 2.399963 + grove_index * 0.47 + layer * 1.3
                spread = 1.2 + math.sqrt(index) * 1.9 + layer * 1.3
                x, z = cx + math.cos(angle) * spread, cz + math.sin(angle) * spread * 0.82
                if abs(x) < hx + 2.4 and abs(z) < hz + 2.4:
                    continue
                size = grove_rng.uniform(0.52, 0.69) if index % 4 == 1 else grove_rng.uniform(0.82, 1.09)
                tree_pair(x, z, species_at(cz, grove_index + index), size, angle, "ForestTree")

    # Understory follows tree groups, retaining open ground between them.
    for index, (x, z, size) in enumerate(site for site in tree_sites if site[0] > 0):
        yaw = rng.uniform(0, math.tau)
        flower_pair("fern_patch", x + 0.55, z + 0.45, size * 0.72, yaw)
        flower_pair("meadow_tuft", x - 0.50, z + 0.65, size * 0.82, yaw + 1.2)
        if index % 6 == 0:
            flower_pair("bluebells" if map_id in ("lake", "ridges") else "daisies",
                        x + 0.8, z - 0.7, size * 0.68, yaw)
        if index % 4 == 0:
            px, pz = x + 1.35, z + 0.45
            if all(clear_site(sign * px, pz, 0.65, road_gap=2.5, yard=5.0) for sign in (-1, 1)):
                for sign in (-1, 1):
                    scene("hazel_thicket", sign * px, pz, size * 0.65, yaw * sign, "Understory", radius=0.50 * size)
        if index % 12 == 0:
            stone_pair(x + 2.2, z - 1.0, rng.uniform(0.48, 0.75), yaw, "ForestRock")

    # Sparse low verges articulate turns and settlement outskirts, instead of
    # putting the same ten plants in a ring around every single building.
    for road_index, segment in enumerate(paths):
        x1, z1, x2, z2 = segment
        length = math.hypot(x2 - x1, z2 - z1)
        if length < 3:
            continue
        nx, nz = -(z2 - z1) / length, (x2 - x1) / length
        for step in range(max(1, int(length / 7.5))):
            t = (step + 0.5) / max(1, int(length / 7.5))
            for sign in (-1, 1):
                x, z = x1 + (x2 - x1) * t + nx * sign * 2.5, z1 + (z2 - z1) * t + nz * sign * 2.5
                if x < 0 or abs(x) > hx or abs(z) > hz:
                    continue
                flower_pair("meadow_tuft", x, z, rng.uniform(0.54, 0.74), road_index)
                if (step + road_index) % 4 == 0:
                    flower_pair("daisies", x + nx * 0.5, z + nz * 0.5, 0.57, road_index)

    for (species, cell_x, cell_z), instances in sorted(batches.items()):
        identifier = f"nature_cover_{species}_{cell_x}_{cell_z}".replace("-", "n")
        buffer = []
        for x, y, z, size, yaw in instances:
            cosine, sine = math.cos(yaw) * size, math.sin(yaw) * size
            buffer.extend((cosine, 0, sine, x, 0, size, 0, y, -sine, 0, cosine, z))
        resources.append(f'[sub_resource type="MultiMesh" id="{identifier}"]\n'
                         f'transform_format = 1\ninstance_count = {len(instances)}\n'
                         f'mesh = ExtResource("nature_{species}_mesh")\n'
                         f'custom_aabb = AABB({cell_x * 32 - 2}, -1, {cell_z * 32 - 2}, 36, 5, 36)\n'
                         f'buffer = PackedFloat32Array({", ".join(f"{value:.6f}" for value in buffer)})')
        nodes.append(f'[node name="{identifier}" type="MultiMeshInstance3D" parent="Nature"]\n'
                     f'multimesh = SubResource("{identifier}")\nmaterial_override = ExtResource("nature_grass_material")\ncast_shadow = 0')
    return externals, resources, nodes
