extends RefCounted
## Licensed source edits; attribution is retained in assets/audio/CREDITS.md.
## Generated by tools/build_war_audio.py. UI/world call sites must match the bus.

const EVENTS: Dictionary = {
	"war_select": {"streams": [preload("res://assets/audio/block_war/war_select_01.wav"), preload("res://assets/audio/block_war/war_select_02.wav")], "gain_db": -1.0, "bus": &"UI", "priority": 2, "gap_ms": 95, "limit": 2},
	"war_drag": {"streams": [preload("res://assets/audio/block_war/war_drag_01.wav"), preload("res://assets/audio/block_war/war_drag_02.wav")], "gain_db": -4.0, "bus": &"UI", "priority": 1, "gap_ms": 140, "limit": 2},
	"war_ratio": {"streams": [preload("res://assets/audio/block_war/war_ratio_01.wav"), preload("res://assets/audio/block_war/war_ratio_02.wav")], "gain_db": -3.0, "bus": &"UI", "priority": 2, "gap_ms": 75, "limit": 2},
	"war_order": {"streams": [preload("res://assets/audio/block_war/war_order_01.wav"), preload("res://assets/audio/block_war/war_order_02.wav")], "gain_db": 0.0, "bus": &"UI", "priority": 3, "gap_ms": 150, "limit": 2},
	"war_denied": {"streams": [preload("res://assets/audio/block_war/war_denied_01.wav")], "gain_db": -1.0, "bus": &"UI", "priority": 4, "gap_ms": 350, "limit": 1},
	"war_cancel": {"streams": [preload("res://assets/audio/block_war/war_cancel_01.wav")], "gain_db": -2.0, "bus": &"UI", "priority": 2, "gap_ms": 130, "limit": 1},
	"war_pause": {"streams": [preload("res://assets/audio/block_war/war_pause_01.wav")], "gain_db": -1.0, "bus": &"UI", "priority": 4, "gap_ms": 180, "limit": 1},
	"war_resume": {"streams": [preload("res://assets/audio/block_war/war_resume_01.wav")], "gain_db": -1.0, "bus": &"UI", "priority": 4, "gap_ms": 180, "limit": 1},
	"war_march": {"streams": [preload("res://assets/audio/block_war/war_march_01.wav"), preload("res://assets/audio/block_war/war_march_02.wav"), preload("res://assets/audio/block_war/war_march_03.wav"), preload("res://assets/audio/block_war/war_march_04.wav")], "gain_db": 2.0, "bus": &"Foley", "priority": 1, "gap_ms": 190, "limit": 2},
	"war_melee": {"streams": [preload("res://assets/audio/block_war/war_melee_01.wav"), preload("res://assets/audio/block_war/war_melee_02.wav"), preload("res://assets/audio/block_war/war_melee_03.wav"), preload("res://assets/audio/block_war/war_melee_04.wav")], "gain_db": -1.0, "bus": &"Combat", "priority": 2, "gap_ms": 130, "limit": 3},
	"war_capture": {"streams": [preload("res://assets/audio/block_war/war_capture_01.wav"), preload("res://assets/audio/block_war/war_capture_02.wav")], "gain_db": 0.0, "bus": &"UI", "priority": 5, "gap_ms": 550, "limit": 2},
	"war_lost": {"streams": [preload("res://assets/audio/block_war/war_lost_01.wav")], "gain_db": 0.0, "bus": &"UI", "priority": 5, "gap_ms": 650, "limit": 1},
	"war_reinforce": {"streams": [preload("res://assets/audio/block_war/war_reinforce_01.wav"), preload("res://assets/audio/block_war/war_reinforce_02.wav")], "gain_db": -2.0, "bus": &"Combat", "priority": 2, "gap_ms": 280, "limit": 2},
	"war_upgrade": {"streams": [preload("res://assets/audio/block_war/war_upgrade_01.wav"), preload("res://assets/audio/block_war/war_upgrade_02.wav")], "gain_db": 1.0, "bus": &"Combat", "priority": 4, "gap_ms": 500, "limit": 2},
	"war_rebuild": {"streams": [preload("res://assets/audio/block_war/war_rebuild_01.wav"), preload("res://assets/audio/block_war/war_rebuild_02.wav")], "gain_db": 1.0, "bus": &"Combat", "priority": 4, "gap_ms": 500, "limit": 2},
	"war_skill_command": {"streams": [preload("res://assets/audio/block_war/war_skill_command_01.wav")], "gain_db": 2.0, "bus": &"Combat", "priority": 5, "gap_ms": 550, "limit": 1},
	"war_skill_drum": {"streams": [preload("res://assets/audio/block_war/war_skill_drum_01.wav")], "gain_db": 2.0, "bus": &"Combat", "priority": 5, "gap_ms": 650, "limit": 1},
	"war_skill_shield": {"streams": [preload("res://assets/audio/block_war/war_skill_shield_01.wav")], "gain_db": 1.0, "bus": &"Combat", "priority": 5, "gap_ms": 650, "limit": 1},
	"war_skill_breach": {"streams": [preload("res://assets/audio/block_war/war_skill_breach_01.wav"), preload("res://assets/audio/block_war/war_skill_breach_02.wav")], "gain_db": 1.0, "bus": &"Combat", "priority": 6, "gap_ms": 500, "limit": 2},
	"war_rabbit_dash": {"streams": [preload("res://assets/audio/block_war/war_rabbit_dash_01.wav")], "gain_db": 1.0, "bus": &"Combat", "priority": 5, "gap_ms": 120, "limit": 2},
	"war_rabbit_seal": {"streams": [preload("res://assets/audio/block_war/war_rabbit_seal_01.wav"), preload("res://assets/audio/block_war/war_rabbit_seal_02.wav")], "gain_db": 1.0, "bus": &"Combat", "priority": 5, "gap_ms": 120, "limit": 2},
	"war_rabbit_recall": {"streams": [preload("res://assets/audio/block_war/war_rabbit_recall_01.wav")], "gain_db": -1.0, "bus": &"Combat", "priority": 5, "gap_ms": 120, "limit": 2},
	"war_rabbit_burrow": {"streams": [preload("res://assets/audio/block_war/war_rabbit_burrow_01.wav"), preload("res://assets/audio/block_war/war_rabbit_burrow_02.wav")], "gain_db": 1.0, "bus": &"Combat", "priority": 5, "gap_ms": 120, "limit": 2},
	"war_projectile_hit": {"streams": [preload("res://assets/audio/block_war/war_projectile_hit_01.wav"), preload("res://assets/audio/block_war/war_projectile_hit_02.wav")], "gain_db": -3.0, "bus": &"Combat", "priority": 3, "gap_ms": 120, "limit": 3},
	"war_victory": {"streams": [preload("res://assets/audio/block_war/war_victory_01.wav")], "gain_db": 0.0, "bus": &"UI", "priority": 7, "gap_ms": 1200, "limit": 1},
	"war_defeat": {"streams": [preload("res://assets/audio/block_war/war_defeat_01.wav")], "gain_db": 0.0, "bus": &"UI", "priority": 7, "gap_ms": 1200, "limit": 1},
}
